### ISSUE TITLE
[Forge] Bungee errors with CoFH packet

### ISSUE THREAD

**Issue by Nentify** [SpigotMC/BungeeCord#1437]
Hello

I updated to CoFH Core 3.0.2 and I'm receiving the error [http://pastebin.com/pTmWDj71] when connecting to the server via Bungee. After talking to @KingLemming - It may be likely because the packet ID is -26 - Is it possible you're checking the packet ID and not allowing a packet ID of -26?

The relevant code is here:
https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/lib/util/helpers/SecurityHelper.java#L39

If you need anymore information, let me know. Any help would be appreciated.

Relavent people: @dualspiral @bloodmc

**Comment by skyboy** [comment]
For further information: This particular packet is being registered on both client&server as is appropriate for it to function, and is used to work around a combination vanilla/forge bug wherein the client-side EntityPlayer's UUID does not match the server-side UUID (fixed by vanilla in 1.8) and is implemented in the vanilla system so it can be done as part of CoFHLib (no requirement for Core). Easiest fix is to forward all unrecognized packets on to the client they're meant for.

**Comment by thinkofdeath** [comment]
Any reason why you aren't using the Plugin Message packet?

**Comment by xanderc2** [comment]
what do you mean with "Plugin Message packet" ?

**Comment by thinkofdeath** [comment]
http://wiki.vg/Protocol#Plugin_Message

**Comment by dualspiral** [comment]
I agree with @thinkofdeath's stance here - this is something that should be using PluginMessages. Indeed, [Forge discourages the use of packets over plugin messages](http://www.minecraftforge.net/forum/index.php/topic,20135.0.html).

As a result, I don't think this is a Bungee issue either - more that the mod should be using PluginMessages instead.

@skyboy 
I've done a very handwavy not tested replacement example thingy of your packet implementation with plugin messages at https://github.com/dualspiral/CoFHLib/commit/372895978d36c5171d799e988f5ce6ee8eb1f276. This may not be 100% correct as I don't do much Forge stuff, but feel free to drop the commit onto your own repo and play about with it - I guess the idea is there!

Finally: any further discussion on my commit should not be done here as any fixes to be made to CoFHLib should be discussed on the CoFHLib issue tracker!

**Comment by KingLemming** [comment]
Adding another handler is an *extremely* heavy solution. We know about channels and the *mods* actually use them. However, we're using a packet specifically to not require CoFHCore for this functionality - this isn't a mod, this is part of a library.

This sort of is a bungee issue, as it works in all cases except with bungee.

**Comment by Slind14** [comment]
"extremely heavy" in which way. Unfortunately I don't see why using best practice is an issue?

Anyways the users probably don't care on which site it is going to be solved but would appreciate a quick solution to be found :)

**Comment by xanderc2** [comment]
I am one of the users that wants this "solution", i'm reading this post everyday :)

**Comment by Xfel** [comment]
Is there any specific reason why you need to use a negative packet id?

**Comment by dualspiral** [comment]
"However, we're using a packet specifically to not require CoFHCore for this functionality - this isn't a mod, this is part of a library."

Plugin messages handlers are a stock Forge thing. I don't see why it needs to rely on your core mod...

**Comment by skyboy** [comment]
I haven't explored more in-depth to see if the channel messages would work as expect (timely processing primarily), though I do know they inflate the packet size from 12 bytes to 109 bytes, and add substantial lingering memory overhead.

**Comment by KingLemming** [comment]
@Slind14 - communication is required, yes. That means moving data from one place to another. Packets. A channel is just a different way of sending a packet.

@Xfel - A negative ID guarantees there is no conflict with Minecraft or Forge, period. There's also no reason Bungee should freak out about it. Zero.

@dualspiral - The Core mod has a channel already established. I'd prefer not adding additional memory bloat just to handle this feature. Again, this really should be solved on Bungee's end as we aren't doing anything unreasonable.

**Comment by dualspiral** [comment]
Ok, now it makes sense as to why you chose to do this - not a dependency issue, but performance (essentially). I still don't think that using plugin message channels would be all that bad, but I'd quite happily accept any evidence to the contrary, and I understand why you've chosen this path. Thanks for explaining that.

To explain why it doesn't work in Bungee - it's not that you are using a negative packet ID, but that you are using a non-Mojang packet. Much of the relavent code is found at:

https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/Protocol.java

I do not know the reasoning for not letting custom packets though - though you have to remember that before blood and I added forge support, Bungee was only for Vanilla servers. You could probably argue it is an oversight of ours to not add custom packets, but at the same time, I'm not sure I'd call it an issue that it's missing.

Will the Bungee leads accept a patch to forward custom packets on? I don't know. That's something to ask them, but I seem to recall that it's not likely. I wonder if there is a halfway house where an API could be added to facilitate custom packets - though by the time it's written, I bet that CoFH will be targetting 1.8 and this particular issue becomes a non-problem.

**Comment by Xfel** [comment]
Actually, Bungee DOES support custom packets, just not those with a negative ID. From what I see there (https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/Protocol.java#L125), this could probably be fixed with a simple range check. However, I don't know where else there are assumptions based on the packet id range.

**Comment by dualspiral** [comment]
Second part of the same line tells a different story.

**Comment by Xfel** [comment]
That is why I proposed an ADDITIONAL id >= 0 check...

**Comment by dualspiral** [comment]
Ok, I'll willing to concede that I might be wrong here and I've been thinking that custom packets won't work incorrectly for all this time. If so, I apologise, I've never worked with custom packets.

That said, I'm sure there was a similar issue on here before that was to do with custom packets and that it got turned down. Ah well.

Anyway, if it is supporting them, then I think that you're right - that's all we should need.

https://github.com/dualspiral/BungeeCord/commit/e6e27ee370c03a629cb2f6e36e9e20024655b011
https://dl.dropboxusercontent.com/u/28705212/BungeeCord.jar

**Comment by dualspiral** [comment]
(Actually, thinking about it, it probably will work. I'm sure there are more packets in vanilla Minecraft that Bungee doesn't register. I feel like a bit of a fool now!)

**Comment by Cozza38** [comment]
Hi @dualspiral,

We've just tested the build and didn't appear to work.

```
java.lang.ArrayIndexOutOfBoundsException: -26
	at net.md_5.bungee.entitymap.EntityMap.rewrite(EntityMap.java:108)
	at net.md_5.bungee.entitymap.EntityMap.rewriteClientbound(EntityMap.java:69)
	at net.md_5.bungee.entitymap.EntityMap_1_7_2.rewriteClientbound(EntityMap_1_7_2.java:45)
	at net.md_5.bungee.entitymap.EntityMap_1_7_6.rewriteClientbound(EntityMap_1_7_6.java:17)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:97)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:83)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dualspiral** [comment]
Will look into it when I get chance.

**Comment by xanderc2** [comment]
Not even working to me,
Any news about the new build "cofh compatible"?

**Comment by devryb** [comment]
Having the same issues as well with cofhcore 3.0.2
http://pastebin.com/hE90bLKp

**Comment by devryb** [comment]
Been running with @dualspiral and @KaiKikuchi changes for a good 10h now without issues.  We are also able to run with modpacks using CoFHcore 3.0.2 now

**Comment by xanderc2** [comment]
dual spiral build is not working to me, and cant find KaiKikuchi buid download...

**Comment by devryb** [comment]
I have it compiled here: http://mc.devcoftb.net/files/BungeeCord.jar

**Comment by Yorkforce** [comment]
Would there be any possibility of getting this fix (https://github.com/SpigotMC/BungeeCord/pull/1283) added to the above bungeecord.jar?

**Comment by Cozza38** [comment]
@Yorkforce 

http://atlas.otegamers.com/BungeeCord.jar

**Comment by Yorkforce** [comment]
Thanks Cozza!

Tested and works great, thumbs up to all the other network owners in this thread as well for keeping Bungeecord and modded servers alive!

**Comment by Cozza38** [comment]
That's odd. We just manually merged then compiled. Will have to take
another stab at it.

**Comment by Yorkforce** [comment]
@Cozza38 
My bad, it seems my issue is related to Cauldron 1388 not bungeecord, I pulled it off the network and had same error.

**Comment by alicheek** [comment]
Really amazing guys its people like you that keep the modded community going :)

**Comment by md-5** [comment]
Rejected -> custom packets not supported.

**Comment by t0rched** [comment]
Status? I need either a patches CoFHCore or Bungee.

**Comment by Janmm14** [comment]
@t0rched try out https://github.com/WaterfallMC/Waterfall
