### ISSUE TITLE
Severe bug / memory leak in nettyio

### ISSUE THREAD

**Issue by AustinCZ** [SpigotMC/BungeeCord#1520]
Hello,
a few days ago, one of my clients bungee server (800+ players) started to crash about 10 times a day. After long investigation, we found out it is because of spambot attacks. Normally, 99% of them do no harm, but some of them are able to crash the server due to some sort of memory leak in nettyIO probably.
This is the specific exception that causes it:
java.lang.IndexOutOfBoundsException: index: 1, length: 4 (expected: range(0, 2))
http://pastebin.com/Fq54aD6P

After this exception, server immediately allocate about 2-4GB of RAM and it is never freed with GC. After 2-3 of these exceptions, the heap is full and GC is going crazy trying to free some memory, but fails, which leads to CPU usage of +-500% and nobody is able to connect until server restart.
I have heap dump (its 250MB compressed: http://files.faika.cz/files/heapdump-1435426290285.hprof.tar.gz)

Problems start after 19:18
![visualvm_memory_sample](https://cloud.githubusercontent.com/assets/1372108/8393826/25d797aa-1d21-11e5-83b7-6ceb3ecf58cd.png)
![visualvm_monitor](https://cloud.githubusercontent.com/assets/1372108/8393827/2f662d18-1d21-11e5-84a5-c7c1ed4d7969.png)
Interesting thing is, even the heap is about 9 GB in size max, the whole jvm process took up to 18 GB of ram. Probably due to direct buffer nettyIO is using.

Startup parameters: /usr/lib/jvm/jdk1.8.0_45/bin/java -d64 -Xms256M -Xmx10G -XX:MaxPermSize=256M -jar BungeeCord.jar no matter what heap size we set, it is the same. Also tried different GC types and settings and Java 7/8.
Tested on bungee Build 1071 and 1057 with or without plugins, it is the same.

For now we end up filtering all strange foreign IP addresses accessing the server to minimize the impacts, but it really is not perfect :/

**Comment by minecrafter** [comment]
Logs from the spambot attack would be useful.

After the attack stops, does forcing a garbage collection help?

**Comment by AustinCZ** [comment]
Here it is http://files.faika.cz/files/proxy.log.1.gz
Look at time 19:21:59, it is the exact time server started allocating memory. (servers time is ahead about 2 minutes over my home computers time where the screenshot was taken)

Forcing GC does not help anything.

**Comment by minecrafter** [comment]
The time you seem to refer to is 19:57:13, as that's when I see your exception consistently appearing.

I will probably recommend @md-5 look into this.

**Comment by AustinCZ** [comment]
No no, i know after 19:57 there are thousands of exceptions, but they dont do anything bad in terms of performance. Server was fine from 19:57:13 until 20:05:28

Everything runned ok until this exact exception:
20:05:28 [SEVERE] [agentrulu531] -> UpstreamBridge - encountered exception
java.lang.IndexOutOfBoundsException: index: 1, length: 4 (expected: range(0, 2))
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1143)
.....

**Comment by ninja-** [comment]
@AustinCZ I saw similiar behaviour but I haven't had logs like you did.
Proxy randomly was filled with unreleased packets and (probably) gc was going crazy and doing lagspikes every 10 seconds.

**Comment by Xayanix** [comment]
It's 100% a bug, we had same.
I had to delete bungeecord...

**Comment by Janmm14** [comment]
@Xayanix that does not help. you just could have killed the process.

**Comment by Samistine** [comment]
I am having issues too, I expierence no real issues until I run out of RAM.
50-60 players:
[img]http://i.imgur.com/uu2gXSU.png[/img]

**Comment by ninja-** [comment]
@md-5 @thinkofdeath anyone looked into this one?

**Comment by Iceee** [comment]
I experienced attacks with similar symptoms as you're seeing, but looking at your heap dump, it's not the exact same.  That said, the following is still potentially the issue:

BungeeCord does not set high/low watermarks, and unconditionally writes to channels regardless of how far behind they are.  Over time, this could starve the application to death.

The following solved my issue so it may help you:
https://github.com/Iceee/BungeeCord/commit/1a997bf95c3832b65aa0a08160a83890594e650d

**Comment by Cazmon** [comment]
any solution?

**Comment by Janmm14** [comment]
try finding someone building bungee with the edits @Iceee linked and test out

**Comment by ninja-** [comment]
@Iceee I'll report if I have any issues like these with your fix

**Comment by minecrafter** [comment]
@Iceee I tried your patch and I am seeing improvements. Here's two `jmap -histo` comparisons.

Bungee with your patch:

     1:       1360509      119724792  io.netty.buffer.PooledUnsafeDirectByteBuf
     2:       2722506       87120192  io.netty.util.Recycler$DefaultHandle
     3:       1360317       87060288  io.netty.channel.ChannelOutboundBuffer$Entry
     4:       1249212       79949568  java.nio.DirectByteBuffer
     5:            54       17161216  [Ljava.nio.ByteBuffer;
     6:        706560       16957440  io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry
     7:         33645       13238856  [I
     8:           565       12499536  [Lio.netty.util.Recycler$DefaultHandle;
     9:         57077        4960672  [C
    10:         82711        4374336  [B
    11:         77201        4323256  io.netty.buffer.UnpooledHeapByteBuf
    12:         45598        3653040  [J
    13:         46137        2952768  io.netty.buffer.PoolSubpage


Bungee without patch:

     1:       5392619      345127616  java.nio.DirectByteBuffer
     2:       3157946      277899248  io.netty.buffer.PooledUnsafeDirectByteBuf
     3:       6319256      202216192  io.netty.util.Recycler$DefaultHandle
     4:       3157889      202104896  io.netty.channel.ChannelOutboundBuffer$Entry
     5:            54       76063520  [Ljava.nio.ByteBuffer;
     6:         95091       53648544  [I
     7:           651       27384048  [Lio.netty.util.Recycler$DefaultHandle;
     8:        706560       16957440  io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry
     9:        119186        9541008  [J
    10:        119725        7662400  io.netty.buffer.PoolSubpage
    11:        101666        7377672  [C
    12:         78866        4548720  [B
    13:         72979        4086824  io.netty.buffer.UnpooledHeapByteBuf

However, take these results with a grain of salt, as the non-patched Bungee has been online for one day longer.

**Comment by Janmm14** [comment]
@ninja- just set compression threshold to -1

**Comment by minecrafter** [comment]
I'm going to be restarting my patched and one of my non-patched Bungees tonight and I will report back with any new results.

So far, @Iceee's patch seems to make the memory leak grow a bit more slowly, so it's not a full fix to the problem, but it seems to delay it somewhat.

I will try another approach: reverting 0d569ac. I will report back if it helps solve the issues.

**Comment by minecrafter** [comment]
I've restarted my three proxies (all with identical plugin setup).

* Proxy 1 is using @Iceee's potential fix.
* Proxy 2 is running [my branch](https://github.com/minecrafter/BungeeCord/tree/remove-native-compression) where I've reverted 0d569ac.
* Proxy 3 is running the latest vanilla version of BungeeCord (as of this writing, [build 1073](http://ci.md-5.net/job/BungeeCord/1073/)).

**Comment by minecrafter** [comment]
Observations after one hour:

* Native compression does have the zero-copy effect intended (lots of byte array garbage show up in the `jmap -histo` output for Proxy 2).
* The patch from @Iceee appears to reduce the amount of memory recovered through GC.

Will post more updates later as this is a low-traffic period.

**Comment by Iceee** [comment]
I'm glad to hear that you're having success.

What I ultimately implemented when I had this issue was a change that kicked and closed connections that are more than X behind instead of simply dropping packets.  When I'm able, I will submit a PR with that change.  The one I posted above should solve the problem in the fewest lines of code though.

**Comment by ninja-** [comment]
@Iceee no problems so far with your patch. Not sure if the bug was random or trigerred by a malicious packet.

I am also going to use compression: -1 in future.

Thanks

@md-5 I can recommend merging @Iceee's patch. But since 1.7 support is still broken master I can't use raw builds anyway...

**Comment by Samistine** [comment]
thanks for the commit, I get about double-triple the run time now :)

**Comment by ninja-** [comment]
@Iceee remember to print a debug when closing a connections like this and include ip and how much it was behind

**Comment by minecrafter** [comment]
Here's some new `jmap -histo` readings in a more active period of time.

It looks like Iceee's patch seems to work well in reducing memory usage, apparently through more aggressive buffer management(?). It doesn't appear to be resolved, but it does appear to slow the memory leak down at least.

@Iceee's patch:
    1:       1197227       67044712  io.netty.buffer.UnpooledHeapByteBuf
    2:        839549       53731136  java.nio.DirectByteBuffer
    3:       1222870       44633640  [B
    4:        506493       44571384  io.netty.buffer.PooledUnsafeDirectByteBuf
    5:       1014252       32456064  io.netty.util.Recycler$DefaultHandle
    6:        506301       32403264  io.netty.channel.ChannelOutboundBuffer$Entry
    7:         99375       22088832  [C
    8:        706560       16957440  io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry
    9:         38365       15273736  [I
    10:        398960        9575040  net.md_5.bungee.protocol.PacketWrapper
    11:          1296        5637184  [Lio.netty.util.Recycler$DefaultHandle;
    12:            74        3765792  [Ljava.nio.ByteBuffer;
    13:          1600        2851840  [Lio.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry;
    14:         74422        1786128  java.lang.String
    15:        111248        1779968  java.lang.Integer
    16:         16064        1290672  [J
    17:         16601        1062464  io.netty.buffer.PoolSubpage
    18:         20627        1022840  [Ljava.lang.Object;
    19:         31332        1002624  java.util.HashMap$Node
    20:         20681         661792  java.util.concurrent.ConcurrentHashMap$Node

Without native compression commit:
    1:        315007       61447528  [B
    2:        854299       54675136  java.nio.DirectByteBuffer
    3:        580957       51124216  io.netty.buffer.PooledUnsafeDirectByteBuf
    4:       1162858       37211456  io.netty.util.Recycler$DefaultHandle
    5:        580935       37179840  io.netty.channel.ChannelOutboundBuffer$Entry
    6:        303902       17018512  io.netty.buffer.UnpooledHeapByteBuf
    7:        706560       16957440  io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry
    8:         18337       11274256  [I
    9:            54        9072384  [Ljava.nio.ByteBuffer;
    10:         51991        6629232  [C
    11:           527        5811824  [Lio.netty.util.Recycler$DefaultHandle;
    12:          1600        2851840  [Lio.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry;
    13:         75153        1803672  net.md_5.bungee.protocol.PacketWrapper
    14:         21136        1695824  [J
    15:         21675        1387200  io.netty.buffer.PoolSubpage
    16:         47846        1148304  java.lang.String
    17:          9028         680600  [Ljava.lang.Object;
    18:         20978         671296  java.util.concurrent.ConcurrentHashMap$Node
    19:          5894         662808  java.lang.Class
    20:         18789         601248  java.util.HashMap$Node

Vanilla BungeeCord (build 1073):
    1:       1405108       78686048  io.netty.buffer.UnpooledHeapByteBuf
    2:       1091348       69846272  java.nio.DirectByteBuffer
    3:       1428958       50237352  [B
    4:        515396       45354848  io.netty.buffer.PooledUnsafeDirectByteBuf
    5:       1031624       33011968  io.netty.util.Recycler$DefaultHandle
    6:        515023       32961472  io.netty.channel.ChannelOutboundBuffer$Entry
    7:         96445       21937584  [C
    8:        706560       16957440  io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry
    9:         37909       12792480  [I
   10:        467804       11227296  net.md_5.bungee.protocol.PacketWrapper
   11:           959        5395760  [Lio.netty.util.Recycler$DefaultHandle;
   12:            54        5268016  [Ljava.nio.ByteBuffer;
   13:          1600        2851840  [Lio.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry;
   14:        115335        1845360  java.lang.Integer
   15:         72686        1744464  java.lang.String
   16:         31107        1318648  [Ljava.lang.Object;
   17:         15838        1272080  [J
   18:         16377        1048128  io.netty.buffer.PoolSubpage
   19:         30442         974144  java.util.HashMap$Node
   20:         20892         668544  java.util.concurrent.ConcurrentHashMap$Node

**Comment by ninja-** [comment]
@thinkofdeath @md-5 any review of @Iceee's patch whether it could be merged?

**Comment by md-5** [comment]
He already knows the changes he needs to make.

**Comment by ninja-** [comment]
alright thanks

**Comment by komiss77** [comment]
Thank you very much! It really works! One small request: could you integrate support for 1.7. * Clients?

**Comment by Xayanix** [comment]
@Iceee 
Fixed my issue.

**Comment by Janmm14** [comment]
@komiss77 that needs a new issue

**Comment by ninja-** [comment]
@AustinCZ @Xayanix @komiss77 @md-5 @thinkofdeath @minecrafter @Janmm14 

the netty bug behind _this bungee bug_ has been https://github.com/netty/netty/issues/3166 which is fixed in netty .25+, bungee uses .24

so I am telling everyone interested: after advanced tests, I am concluding that it's safe to update to .30.
I had a little discussion with netty about the behaviour of .30 regarding recyclers but wasn't exactly a bug and was probably caused by me using TCP_NODELAY(?) over bungee's default settings.

**Comment by md-5** [comment]
Closing this bug per what ninja- said (bungee has been updated). I fail to see a way in which the above scenario mentioned could be encountered with a Vanilla configuration (otherwise Vanilla/CraftBukkit/Spigot would have the same issue), and after reviewing the initial heap dump, I'm going to go out on a limb and say AnimatedMotd or variants thereof (which hack into Bungee's internals) are allowing malicious clients to easily run up a large packet buffer.
