### ISSUE TITLE
Two players with the same name can't be online at the same time.

### ISSUE THREAD

**Issue by Xadzkon** [SpigotMC/BungeeCord#2544]
I have done some experimenting with Bungee and how it handles logins, and I have discovered a behavior that might have been intended, but not well thought through.

My tests were done in offline mode, but it not only would probably work in online mode as well, it could cause issues in very rare occasions.

I have used a (premium, but this shouldn't make a difference) Minecraft account to connect to a Bungee server from two separate instances of Minecraft. First I connected with one instance, everything like normal. However, when I connected with the second instance of Minecraft, with my custom made plugin, I have modified the UUID of the connecting player on PreLoginEvent. So the player connecting in the second connection will have a different UUID from the first one. Even though, based on UUIDs, there were now two different players connecting to the server, Bungee still has kicked me with the message "You are already connected to this proxy!". The only cause of this issue can be that Bungee determines whether a player is already logged in is based on the name of the player, and not the UUID.

Now this doesn't make a difference in most scenarios, as you probably wouldn't want two different players with the same username connected if you are running an offline server, however if you are running an online mode server, it would mean that if two premium players have the same name, which there are some, and want to play on the server at the same time, this could make them unable to play at the same time, even though they have different UUIDs.

As to why I was needing this, I am working on a plugin, where I basically differentiate online and offline mode players, and for one of the workarounds that it needed, this was necessary to work. Now I have to get a new workaround for the original problem of the lack of an API call that I would need, probably do something with packets or make a fork or an injector. :P

**Comment by Janmm14** [comment]
Spigot servers and vanilla can't handle that too.
My suggestion would be to try getting an event before the check is done, or if thats not enough, you could remove the check from bungee (for example forking) and check it in a later event yourself.
Then you should at max allow the cracked player whichs name is currently unavailable to tell him that he needs to change his name and reclaim his account with a password then which will cause its uuid to be changed.

**Comment by Xadzkon** [comment]
Thanks for your reply. I remember that Spigot accepts two players with the same name, but capitalized differently.

Also, it might be a little bit offtopic, but do you know where exactly in the BungeeCord code is PendingConnection (which you get with LoginEvent event.getConnection() ) being created?
Thanks if you can answer that.

**Comment by Black-Hole** [comment]
> if two premium players have the same name, which there are some
No, Mojang won't allow two accounts to use the same name (case insensitive) at any given time.

All the issues you're trying to solve are already solved by plugins like AuthmeReloaded.

**Comment by Xadzkon** [comment]
Believe it or not, there are accounts with the same name. Check this out: https://en.namemc.com/name/juggernaut also https://en.namemc.com/search?q=Thor - just after a quick Google search.

How do you know that what I am trying to solve is solved by AuthMe? I haven't even mentioned what I am trying to do. It's not solved by AuthMe...

**Comment by Black-Hole** [comment]
There are some invalid game profiles which are returned by some Mojang services. But Mojang says that they are deleted from the main database. See for instance https://bugs.mojang.com/browse/WEB-117

So it's impossible for the Mojang auth servers to have two game profiles for the same name (case insensitive) at any given time.

**Comment by Janmm14** [comment]
@Xadzkon Likely inside the InitialHandler.

**Comment by Xadzkon** [comment]
@Janmm14 Yeah, I have found that out as well. Since I have managed to do what I like with reflections =)

**Comment by Xadzkon** [comment]
@Black-Hole Wait, they delete user accounts? That doesn't make sense, because people have payed for them. Evil Mojang :(

**Comment by md-5** [comment]
Allowing this would screw with plugins bad
