### ISSUE TITLE
Players invisible in 1.16 where bungee is online mode but IP forwarding not enabled

### ISSUE THREAD

**Issue by Cheos137** [SpigotMC/BungeeCord#2942]
when using the latest build of bungeecord (# 1530) and playing in minecraft 1.16.1 and 1.16.2,
all players appear invisible to you
This does not affect players using versions below 1.16 (everything appears normal then)

To reproduce: setup a bungeecord with any subserver and join with 2 minecraft clients, one in 1.15.2 (or below) and another one in any 1.16 version. The 1.15.2 Player will be able to see the player playing in 1.16, but not the other way around.

**Comment by Dj-jom2x** [comment]
fix this please

**Comment by ninjamaster4427** [comment]
This is also still an issue in the 371 waterfall build for anyone else reading this thread to investigate their server issues.

**Comment by md-5** [comment]
Issue only occurs if you have an online mode bungeecord with ip forwarding disabled.
While the issue shouldn't occur (though perhaps is a result of something Mojang did to reduce piracy), it is almost certainly also a configuration error on your end.

**Comment by wpcwzy** [comment]
> Issue only occurs if you have an online mode bungeecord with ip forwarding disabled.
> While the issue shouldn't occur (though perhaps is a result of something Mojang did to reduce piracy), it is almost certainly also a configuration error on your end.

So this issue might be temporarily solved by enabling online mode and ip forwarding at the same time?

**Comment by md-5** [comment]
I cannot think under what circumstances you would need to have an online mode bungee with a non ip forwarded server --- even pre 1.16 this would result in broken skins and mismatched UUIDs. It is a configuration issue on your end.

**Comment by ninjamaster4427** [comment]
My IP-forwarding is on for my config.yml of the Waterfall server.

**Comment by GreatestSyn** [comment]
SOOOO... ... My online mode is enabled on bungeecord and my ip forwarding is enabled... but still can't see anyone else on ther server... :( HELP?

**Comment by Cheos137** [comment]
> I cannot think under what circumstances you would need to have an online mode bungee with a non ip forwarded server --- even pre 1.16 this would result in broken skins, useless IP addresses, and mismatched UUIDs. It is a configuration issue on your end.
I do have forge 1.8 (modpack) servers within the network which I cannot connect to with ipforwarding enabled, although I want the overall network to be in online mode.
About broken skins and mismatched UUIDs, I didn't come across any of theese problems (even if all my backed servers are using offline UUIDs)

Might there anything else I could do to get visible players in 1.16+?

**Comment by ninjamaster4427** [comment]
I have ip-forwarding on for my server and this is still an issue.

**Comment by henryoce** [comment]
Hi @md-5 .
> Issue only occurs if you have an online mode bungeecord with ip forwarding disabled.

Bungee is online-mode and ip forwarding is ENABLED.
Yet I still have this issue, along with many others.

>it is almost certainly also a configuration error on your end.

Okay.. "configuration error", might need something more specific thanks. 
That's like saying my car does not start because I have broken it.

Please advise of any workarounds in the meantime and if this is on your radar to fix.

**Comment by md-5** [comment]
I cannot reproduce any issue not in the circumstances I have described above.
Remove all plugins and see if the issue persists.

**Comment by ninjamaster4427** [comment]
I removed all plugins and still had the issue with ip-forwarding on and enabled online mode.

**Comment by ninjamaster4427** [comment]
Waterfall is reporting this as an upstream spigot issue. Is that incorrect? https://github.com/PaperMC/Waterfall/issues/564

**Comment by Rev-Zareh** [comment]
I am having the same issue with a Bungeecord server I just created and paper as my lobby server.

Any word on how to resolve it?

**Comment by G2Math** [comment]
Hello, I have done testing removing all plugins, When using a bungeecord setup with online mode and ip forwarding enabled, players on the next server are not visible when removing the bungeecord and connecting directly to the regular server players are visible. This test was done in 1.16.2. Further note, online mode was not enabled on the regular server.

**Comment by GreatestSyn** [comment]
@md-5 what configuration settings should I have to fix your errors?

**Comment by Rev-Zareh** [comment]
I believe I resolved the issue on my end. Tested with several players and it works.

Really a rookie mistake. The first thing I changed was in the bukkit.yml for each server and changed the connection-throttle from 4000 to -1

The next thing I noticed was I needed to go into the spigot.yml for each server and change bungeecord from "False" to "True".

Everything is working as it should be.

**Comment by ninjamaster4427** [comment]
Setting the connection-throttle = -1 and bungeecord to true worked. But why was this not an issue in 1.16.1? Should that not be investigated? Thank you, @Rev-Zareh !

**Comment by md-5** [comment]
I literally said above, when you have online mode bungeecord = true is required

**Comment by ninjamaster4427** [comment]
Bungeecord = true on the servers is not the same as online-mode = true. That was the confusion as you seemed to combine them into "online mode bungeecord."

**Comment by Rev-Zareh** [comment]
> Bungeecord = true on the servers is not the same as online-mode = true. That was the confusion as you seemed to combine them into "online mode bungeecord." Still odd that it was working pre-1.16.2 with those incorrect settings. I wonder what changed.

No problem @ninjamaster4427.

Very true.

I noticed browsing through other responses, some seem to be a bit grumpy with this whole support thing lol. Some of us aren't as knowledgeable about the configs and settings, etc. We come to the forums and support for, uh, support. It would be nice that there were more pleasant members without being so short in their responses. Maybe it's just me being in customer service and management most of my life, but just an observation ;)

**Comment by Janmm14** [comment]
> 
> 
> > Bungeecord = true on the servers is not the same as online-mode = true. That was the confusion as you seemed to combine them into "online mode bungeecord." Still odd that it was working pre-1.16.2 with those incorrect settings. I wonder what changed.
> 
> No problem @ninjamaster4427.
> 
> Very true.
> 
> I noticed browsing through other responses, some seem to be a bit grumpy with this whole support thing lol. Some of us aren't as knowledgeable about the configs and settings, etc. We come to the forums and support for, uh, support. It would be nice that there were more pleasant members without being so short in their responses. Maybe it's just me being in customer service and management most of my life, but just an observation ;)

the difference between github issues, spigotmc forums and "customer service" is, that BungeeCord and support for it is provided totally free and with contributions from community members.
So don't expect this to be equal to "customer service"

**Comment by Fallen-Breath** [comment]
> Issue only occurs if you have an online mode bungeecord with ip forwarding disabled.
With older bungeecord version (<=build1529) there is no player invisible issue with onlinemode true and ipforwarding false. There might be some changes in the code after build1530 that cause this issue

**Comment by Rev-Zareh** [comment]
> > > Bungeecord = true on the servers is not the same as online-mode = true. That was the confusion as you seemed to combine them into "online mode bungeecord." Still odd that it was working pre-1.16.2 with those incorrect settings. I wonder what changed.
> > 
> > 
> > No problem @ninjamaster4427.
> > Very true.
> > I noticed browsing through other responses, some seem to be a bit grumpy with this whole support thing lol. Some of us aren't as knowledgeable about the configs and settings, etc. We come to the forums and support for, uh, support. It would be nice that there were more pleasant members without being so short in their responses. Maybe it's just me being in customer service and management most of my life, but just an observation ;)
> 
> the difference between github issues, spigotmc forums and "customer service" is, that BungeeCord and support for it is provided totally free and with contributions from community members.
> So don't expect this to be equal to "customer service"

LMAO 😆😂🤣

**Comment by md-5** [comment]
>With older bungeecord version (<=build1529) there is no player invisible issue with onlinemode true and ipforwarding false. There might be some changes in the code after build1530 that cause this issue

The code changes are almost certainly in the client, not bungee

**Comment by Leymooo** [comment]
@md-5 in build 1530 was disabled entity metadata rewriting for 1.16+.  This is cause this issue with `bungeecord = false`.

TabList rewrite changes UUID from offline to online uuid(https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/tab/TabList.java#L37)
Then server sends SpawnPlayer with offline uuid (https://wiki.vg/Protocol#Spawn_Player)
And client skips SpawnPlayer packet because UUID in PlayerListItem and in SpawnPlayer are different but they should be same.

**Comment by md-5** [comment]
Thanks @Leymooo , its been reenabled
